extends:
- eslint:recommended
- next/core-web-vitals
- prettier
rules:
  quotes: [error, double]
  semi: [error, always]
  no-multiple-empty-lines: [error, { max: 1, maxEOF: 1 }]
  no-trailing-spaces: [error, { skipBlankLines: true }]
  no-console: [error, { allow: [warn, error] }]
  no-unused-vars: warn
  no-dupe-keys: error
  arrow-parens: [error, as-needed]
  comma-dangle: [error, always-multiline]
  prefer-const: error
  prefer-destructuring: [error, { object: true, array: false }]
  prefer-spread: error
  prefer-template: error
  no-mixed-spaces-and-tabs: error
  eqeqeq: [error, always]
  indent: [error, 2, { SwitchCase: 1 }]
  max-len: [error, { code: 120, ignoreComments: true, ignoreStrings: true, ignoreTemplateLiterals: true }]
  array-bracket-spacing: [error, never]
  comma-spacing: [error, { before: false, after: true }]
  object-curly-spacing: [error, always]
ignorePatterns:
- .next
- node_modules
- "*.d.ts"
